import type { University, Program, Review, Scholarship } from './types';

function makeProgram(
  id: string,
  name: string,
  degree: string,
  faculty: string,
  credits: number,
  duration: string,
  tuitionPerCredit: number,
  admissionFee: number,
  labFee: number,
  intakeSeasons: string[] = ['Spring', 'Summer', 'Fall'],
  weekend = false,
  online = false
): Program {
  return {
    id,
    name,
    degree,
    faculty,
    credits,
    duration,
    tuitionPerCredit,
    admissionFee,
    labFee,
    libraryFee: 2000,
    otherFee: 3000,
    scholarshipAvailable: true,
    minCgpa: 3.0,
    intakeSeasons,
    weekend,
    online,
  };
}

function makeReview(
  id: string,
  author: string,
  rating: number,
  text: string,
  verified = true
): Review {
  return {
    id,
    author,
    verified,
    date: '2025-0' + (Math.floor(Math.random() * 8) + 1) + '-15',
    rating,
    categories: {
      teachers: rating,
      campus: Math.min(5, rating + (Math.random() > 0.5 ? 1 : 0)),
      labs: Math.max(3, rating - (Math.random() > 0.5 ? 1 : 0)),
      environment: rating,
      career: Math.max(3, rating - (Math.random() > 0.5 ? 1 : 0)),
      library: Math.min(5, rating + (Math.random() > 0.5 ? 1 : 0)),
    },
    text,
  };
}

const standardScholarships: Scholarship[] = [
  {
    id: 'merit',
    name: 'Merit Scholarship',
    type: 'Merit-based',
    waiver: '25%–100%',
    condition: 'Based on SSC & HSC GPA results',
    minCgpa: 4.5,
  },
  {
    id: 'need',
    name: 'Need-based Scholarship',
    type: 'Financial Aid',
    waiver: '20%–50%',
    condition: 'Based on family income and academic merit',
    minCgpa: 3.0,
  },
  {
    id: 'sibling',
    name: 'Sibling Discount',
    type: 'Family',
    waiver: '25%',
    condition: 'For siblings studying at the same university',
    minCgpa: 3.0,
  },
  {
    id: 'freedom',
    name: 'Freedom Fighter Quota',
    type: 'Government Quota',
    waiver: '100%',
    condition: 'Children of freedom fighters',
    minCgpa: 3.0,
  },
  {
    id: 'female',
    name: 'Female Student Scholarship',
    type: 'Gender',
    waiver: '10%–20%',
    condition: 'Encouraging female enrollment',
    minCgpa: 3.0,
  },
];

const standardFacilities = [
  'WiFi Campus',
  'Central Library',
  'Computer Labs',
  'Research Labs',
  'Medical Center',
  'Prayer Room',
  'Sports Complex',
  'Auditorium',
  'Cafeteria',
  'Parking',
];

const standardClubs = [
  'Programming Club',
  'Cultural Club',
  'Debate Club',
  'Sports Club',
  'Photography Club',
  'Robotics Club',
];

// ── Detailed universities (full data) ──────────────────────────────

const buet: University = {
  id: 'aust',
  slug: 'aust',
  name: 'Ahsanullah University of Science and Technology',
  shortName: 'AUST',
  logoColor: '#1e40af',
  established: 1995,
  ugcApproved: true,
  type: 'Private',
  permanentCampus: true,
  city: 'Dhaka',
  address: '141 & 142, Love Road, Tejgaon, Dhaka-1208',
  website: 'https://www.aust.edu',
  phone: '+880 2 8870421',
  email: 'info@aust.edu',
  viceChancellor: 'Prof. Dr. Md. Fazli Ilahi',
  students: 9000,
  faculty: 450,
  campusArea: '5.5 acres',
  semesterSystem: 'Semester (3 per year)',
  iebAccredited: true,
  iebDepartments: ['CSE', 'EEE', 'CE', 'ME', 'IPE', 'Arch'],
  ranking: 1,
  qsRanking: 'Not ranked',
  tuitionRange: [4500, 6500],
  hasHostel: false,
  hasTransport: true,
  hasScholarship: true,
  socialLinks: { facebook: 'https://facebook.com/aust.edu.bd' },
  programs: [
    makeProgram('aust-cse', 'BSc in Computer Science & Engineering', 'BSc', 'Engineering', 160, '4 Years', 5500, 25000, 15000),
    makeProgram('aust-eee', 'BSc in Electrical & Electronic Engineering', 'BSc', 'Engineering', 160, '4 Years', 5500, 25000, 15000),
    makeProgram('aust-ce', 'BSc in Civil Engineering', 'BSc', 'Engineering', 160, '4 Years', 5500, 25000, 15000),
    makeProgram('aust-me', 'BSc in Mechanical Engineering', 'BSc', 'Engineering', 160, '4 Years', 5500, 25000, 15000),
    makeProgram('aust-arch', 'Bachelor of Architecture', 'B.Arch', 'Architecture', 190, '5 Years', 5500, 25000, 15000),
    makeProgram('aust-bba', 'Bachelor of Business Administration', 'BBA', 'Business', 120, '4 Years', 4500, 20000, 5000),
  ],
  scholarships: standardScholarships,
  reviews: [
    makeReview('r1', 'Tanvir H.', 5, 'Excellent engineering university with strong IEB accreditation. The faculty is very supportive and lab facilities are top-notch.'),
    makeReview('r2', 'Nusrat J.', 4, 'Great academic environment but no permanent campus hostel. Location is convenient in Tejgaon.'),
    makeReview('r3', 'Rakib A.', 5, 'One of the best for engineering. IEB accreditation gives a real edge in the job market.'),
  ],
  facilities: [...standardFacilities, 'Innovation Center', 'AI Lab'],
  clubs: [...standardClubs, 'IEEE Student Branch', 'ACM Student Chapter'],
  careerStats: {
    employmentRate: 92,
    topRecruiters: ['Samsung R&D', 'Telenor Health', 'Beximco', 'BRAC', 'Brain Station 23'],
    averageSalary: 'BDT 45,000–60,000/month',
    internshipSupport: true,
  },
  dataSources: {
    source: 'UGC Bangladesh, AUST Official Website',
    lastUpdated: 'June 2026',
    verified: true,
  },
  description: 'Ahsanullah University of Science and Technology (AUST) is one of the top-ranked private engineering universities in Bangladesh, known for its strong IEB accreditation and rigorous academic standards.',
  campusImages: [
    'https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/256431/pexels-photo-256431.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
};

const brac: University = {
  id: 'brac',
  slug: 'brac-university',
  name: 'BRAC University',
  shortName: 'BRACU',
  logoColor: '#b91c1c',
  established: 2001,
  ugcApproved: true,
  type: 'Private',
  permanentCampus: true,
  city: 'Dhaka',
  address: '66 Mohakhali, Dhaka-1212',
  website: 'https://www.bracu.ac.bd',
  phone: '+880 2 9844055',
  email: 'info@bracu.ac.bd',
  viceChancellor: 'Prof. Syed Ferhat Anwar',
  students: 12000,
  faculty: 600,
  campusArea: 'Merul Badda Campus (Permanent)',
  semesterSystem: 'Semester (3 per year)',
  iebAccredited: false,
  iebDepartments: [],
  ranking: 2,
  qsRanking: 'QS Asia 2025: #551-600',
  tuitionRange: [5500, 8500],
  hasHostel: true,
  hasTransport: true,
  hasScholarship: true,
  socialLinks: { facebook: 'https://facebook.com/bracu' },
  programs: [
    makeProgram('brac-cse', 'BSc in Computer Science & Engineering', 'BSc', 'Engineering', 128, '4 Years', 7800, 30000, 12000),
    makeProgram('brac-eee', 'BSc in Electrical & Electronic Engineering', 'BSc', 'Engineering', 128, '4 Years', 7800, 30000, 12000),
    makeProgram('brac-bba', 'Bachelor of Business Administration', 'BBA', 'Business', 120, '4 Years', 6500, 25000, 5000),
    makeProgram('brac-arch', 'Bachelor of Architecture', 'B.Arch', 'Architecture', 172, '5 Years', 7800, 30000, 12000),
    makeProgram('brac-eco', 'BSc in Economics', 'BSc', 'Science', 120, '4 Years', 6500, 25000, 3000),
    makeProgram('brac-llb', 'LLB (Hons)', 'LLB', 'Law', 120, '4 Years', 6500, 25000, 3000),
  ],
  scholarships: standardScholarships,
  reviews: [
    makeReview('r1', 'Sadia R.', 5, 'BRAC University has an amazing campus and incredible faculty. The CSE department is one of the best in the country.'),
    makeReview('r2', 'Mahin K.', 4, 'Great university with strong industry connections. Tuition is on the higher side but worth it.'),
    makeReview('r3', 'Farhana A.', 5, 'The new permanent campus is world-class. Library and research facilities are excellent.'),
  ],
  facilities: [...standardFacilities, 'Swimming Pool', 'Innovation Center', 'AI Lab', 'Research Center'],
  clubs: [...standardClubs, 'IEEE Student Branch', 'ACM Student Chapter', 'Business Club', 'Economics Club'],
  careerStats: {
    employmentRate: 95,
    topRecruiters: ['Google', 'Microsoft', 'Samsung R&D', 'Grameenphone', 'Unilever'],
    averageSalary: 'BDT 50,000–70,000/month',
    internshipSupport: true,
  },
  dataSources: {
    source: 'UGC Bangladesh, BRAC University Official Website',
    lastUpdated: 'June 2026',
    verified: true,
  },
  description: 'BRAC University is one of the top-ranked private universities in Bangladesh, known for its world-class campus, research output, and strong industry connections.',
  campusImages: [
    'https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/256431/pexels-photo-256431.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
};

const nsu: University = {
  id: 'nsu',
  slug: 'north-south-university',
  name: 'North South University',
  shortName: 'NSU',
  logoColor: '#0f766e',
  established: 1992,
  ugcApproved: true,
  type: 'Private',
  permanentCampus: true,
  city: 'Dhaka',
  address: 'Block B, Bashundhara R/A, Dhaka-1229',
  website: 'https://www.northsouth.edu',
  phone: '+880 2 55668200',
  email: 'info@northsouth.edu',
  viceChancellor: 'Prof. Atiqul Islam',
  students: 25000,
  faculty: 800,
  campusArea: 'Bashundhara Campus',
  semesterSystem: 'Semester (3 per year)',
  iebAccredited: false,
  iebDepartments: [],
  ranking: 3,
  qsRanking: 'QS Asia 2025: #651-700',
  tuitionRange: [5000, 8000],
  hasHostel: true,
  hasTransport: true,
  hasScholarship: true,
  socialLinks: { facebook: 'https://facebook.com/northsouthuniversity' },
  programs: [
    makeProgram('nsu-cse', 'BSc in Computer Science & Engineering', 'BSc', 'Engineering', 136, '4 Years', 7500, 28000, 10000),
    makeProgram('nsu-eee', 'BSc in Electrical & Electronic Engineering', 'BSc', 'Engineering', 136, '4 Years', 7500, 28000, 10000),
    makeProgram('nsu-bba', 'Bachelor of Business Administration', 'BBA', 'Business', 120, '4 Years', 6000, 25000, 4000),
    makeProgram('nsu-eco', 'BSc in Economics', 'BSc', 'Science', 120, '4 Years', 6000, 25000, 3000),
    makeProgram('nsu-arch', 'Bachelor of Architecture', 'B.Arch', 'Architecture', 172, '5 Years', 7500, 28000, 10000),
    makeProgram('nsu-llb', 'LLB (Hons)', 'LLB', 'Law', 120, '4 Years', 6000, 25000, 3000),
    makeProgram('nsu-mba', 'Master of Business Administration', 'MBA', 'Business', 60, '2 Years', 8000, 30000, 4000, ['Spring', 'Fall']),
  ],
  scholarships: standardScholarships,
  reviews: [
    makeReview('r1', 'Arif H.', 4, 'NSU has a huge campus and great business school. The CSE department is also strong with good industry connections.'),
    makeReview('r2', 'Tania S.', 5, 'Best private university for BBA. The campus life is vibrant with lots of clubs and activities.'),
    makeReview('r3', 'Sajid R.', 4, 'Good university but tuition is expensive. Scholarships help a lot though.'),
  ],
  facilities: [...standardFacilities, 'Swimming Pool', 'Innovation Center', 'Research Center', 'Gym'],
  clubs: [...standardClubs, 'IEEE Student Branch', 'ACM Student Chapter', 'Business Club', 'Economics Club', 'Drama Club'],
  careerStats: {
    employmentRate: 90,
    topRecruiters: ['Unilever', 'BAT', 'Grameenphone', 'Standard Chartered', 'KPMG'],
    averageSalary: 'BDT 45,000–65,000/month',
    internshipSupport: true,
  },
  dataSources: {
    source: 'UGC Bangladesh, NSU Official Website',
    lastUpdated: 'June 2026',
    verified: true,
  },
  description: 'North South University (NSU) is the first private university in Bangladesh, offering a wide range of programs with a strong reputation in business and engineering education.',
  campusImages: [
    'https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/256431/pexels-photo-256431.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
};

const iub: University = {
  id: 'iub',
  slug: 'independent-university-bangladesh',
  name: 'Independent University, Bangladesh',
  shortName: 'IUB',
  logoColor: '#1d4ed8',
  established: 1993,
  ugcApproved: true,
  type: 'Private',
  permanentCampus: true,
  city: 'Dhaka',
  address: 'Plot 16, Block B, Aftabuddin Ahmed Road, Bashundhara R/A, Dhaka',
  website: 'https://www.iub.edu.bd',
  phone: '+880 2 8431645',
  email: 'info@iub.edu.bd',
  viceChancellor: 'Prof. Tanweer Hasan',
  students: 8000,
  faculty: 400,
  campusArea: 'Bashundhara Campus',
  semesterSystem: 'Semester (3 per year)',
  iebAccredited: false,
  iebDepartments: [],
  ranking: 4,
  qsRanking: 'Not ranked',
  tuitionRange: [4500, 7000],
  hasHostel: true,
  hasTransport: true,
  hasScholarship: true,
  socialLinks: { facebook: 'https://facebook.com/IUB.Official' },
  programs: [
    makeProgram('iub-cse', 'BSc in Computer Science & Engineering', 'BSc', 'Engineering', 136, '4 Years', 6500, 25000, 10000),
    makeProgram('iub-eee', 'BSc in Electrical & Electronic Engineering', 'BSc', 'Engineering', 136, '4 Years', 6500, 25000, 10000),
    makeProgram('iub-bba', 'Bachelor of Business Administration', 'BBA', 'Business', 120, '4 Years', 5500, 20000, 4000),
    makeProgram('iub-eco', 'BSc in Economics', 'BSc', 'Science', 120, '4 Years', 5500, 20000, 3000),
    makeProgram('iub-eee-ph', 'BSc in Electronic Engineering (Green Energy)', 'BSc', 'Engineering', 136, '4 Years', 6500, 25000, 10000),
  ],
  scholarships: standardScholarships,
  reviews: [
    makeReview('r1', 'Nadia F.', 4, 'IUB has a beautiful campus and good faculty. The environmental science program is unique.'),
    makeReview('r2', 'Rashed K.', 4, 'Good university with a focus on liberal arts education. Small class sizes are a plus.'),
  ],
  facilities: [...standardFacilities, 'Research Center', 'Innovation Center'],
  clubs: [...standardClubs, 'IEEE Student Branch', 'Environment Club'],
  careerStats: {
    employmentRate: 88,
    topRecruiters: ['Grameenphone', 'Unilever', 'BRAC', 'World Bank'],
    averageSalary: 'BDT 40,000–55,000/month',
    internshipSupport: true,
  },
  dataSources: {
    source: 'UGC Bangladesh, IUB Official Website',
    lastUpdated: 'June 2026',
    verified: true,
  },
  description: 'Independent University, Bangladesh (IUB) is known for its liberal arts approach and strong environmental science programs.',
  campusImages: [
    'https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
};

const aiub: University = {
  id: 'aiub',
  slug: 'aiub',
  name: 'American International University–Bangladesh',
  shortName: 'AIUB',
  logoColor: '#dc2626',
  established: 1994,
  ugcApproved: true,
  type: 'Private',
  permanentCampus: true,
  city: 'Dhaka',
  address: '408/1, Kuratoli, Khilkhet, Dhaka-1229',
  website: 'https://www.aiub.edu',
  phone: '+880 2 28892138',
  email: 'info@aiub.edu',
  viceChancellor: 'Prof. Dr. Saiful Islam',
  students: 15000,
  faculty: 500,
  campusArea: 'Kuratoli Campus',
  semesterSystem: 'Semester (3 per year)',
  iebAccredited: true,
  iebDepartments: ['CSE', 'EEE'],
  ranking: 5,
  qsRanking: 'Not ranked',
  tuitionRange: [4000, 6000],
  hasHostel: false,
  hasTransport: true,
  hasScholarship: true,
  socialLinks: { facebook: 'https://facebook.com/aiub.edu' },
  programs: [
    makeProgram('aiub-cse', 'BSc in Computer Science & Engineering', 'BSc', 'Engineering', 144, '4 Years', 5500, 20000, 12000),
    makeProgram('aiub-eee', 'BSc in Electrical & Electronic Engineering', 'BSc', 'Engineering', 144, '4 Years', 5500, 20000, 12000),
    makeProgram('aiub-bba', 'Bachelor of Business Administration', 'BBA', 'Business', 120, '4 Years', 4500, 18000, 4000),
    makeProgram('aiub-cse-soft', 'BSc in Software Engineering', 'BSc', 'Engineering', 144, '4 Years', 5500, 20000, 12000),
    makeProgram('aiub-arch', 'Bachelor of Architecture', 'B.Arch', 'Architecture', 172, '5 Years', 5500, 20000, 12000),
  ],
  scholarships: standardScholarships,
  reviews: [
    makeReview('r1', 'Hasan M.', 4, 'AIUB has good engineering programs with IEB accreditation. The campus is modern and well-equipped.'),
    makeReview('r2', 'Sumaiya A.', 4, 'Good university for CSE. Faculty is helpful and there are lots of tech events.'),
  ],
  facilities: [...standardFacilities, 'Innovation Center', 'Research Labs'],
  clubs: [...standardClubs, 'IEEE Student Branch', 'ACM Student Chapter'],
  careerStats: {
    employmentRate: 87,
    topRecruiters: ['Samsung R&D', 'Brain Station 23', 'Telenor Health', 'Enosis'],
    averageSalary: 'BDT 40,000–55,000/month',
    internshipSupport: true,
  },
  dataSources: {
    source: 'UGC Bangladesh, AIUB Official Website',
    lastUpdated: 'June 2026',
    verified: true,
  },
  description: 'American International University–Bangladesh (AIUB) is a leading private university with IEB-accredited engineering programs and a modern campus.',
  campusImages: [
    'https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
};

const ewu: University = {
  id: 'ewu',
  slug: 'east-west-university',
  name: 'East West University',
  shortName: 'EWU',
  logoColor: '#15803d',
  established: 1995,
  ugcApproved: true,
  type: 'Private',
  permanentCampus: true,
  city: 'Dhaka',
  address: 'A/2 Jahurul Islam Avenue, Jahurul Islam City, Aftabnagar, Dhaka',
  website: 'https://www.ewubd.edu',
  phone: '+880 2 28813058',
  email: 'info@ewubd.edu',
  viceChancellor: 'Prof. Dr. M. M. Shahidul Hassan',
  students: 12000,
  faculty: 450,
  campusArea: 'Aftabnagar Campus',
  semesterSystem: 'Semester (3 per year)',
  iebAccredited: false,
  iebDepartments: [],
  ranking: 6,
  qsRanking: 'Not ranked',
  tuitionRange: [3500, 5500],
  hasHostel: false,
  hasTransport: true,
  hasScholarship: true,
  socialLinks: { facebook: 'https://facebook.com/ewubd' },
  programs: [
    makeProgram('ewu-cse', 'BSc in Computer Science & Engineering', 'BSc', 'Engineering', 144, '4 Years', 5000, 18000, 8000),
    makeProgram('ewu-eee', 'BSc in Electrical & Electronic Engineering', 'BSc', 'Engineering', 144, '4 Years', 5000, 18000, 8000),
    makeProgram('ewu-bba', 'Bachelor of Business Administration', 'BBA', 'Business', 120, '4 Years', 4000, 15000, 3000),
    makeProgram('ewu-eco', 'BSc in Economics', 'BSc', 'Science', 120, '4 Years', 4000, 15000, 3000),
    makeProgram('ewu-llb', 'LLB (Hons)', 'LLB', 'Law', 120, '4 Years', 4000, 15000, 3000),
  ],
  scholarships: standardScholarships,
  reviews: [
    makeReview('r1', 'Kabir A.', 4, 'EWU offers good value for money. The CSE department is solid and tuition is reasonable.'),
    makeReview('r2', 'Rifat S.', 4, 'Good university with a convenient location in Aftabnagar. Faculty is experienced.'),
  ],
  facilities: [...standardFacilities, 'Research Center'],
  clubs: [...standardClubs, 'IEEE Student Branch', 'Business Club'],
  careerStats: {
    employmentRate: 85,
    topRecruiters: ['Grameenphone', 'BRAC', 'Beximco', 'Brain Station 23'],
    averageSalary: 'BDT 35,000–50,000/month',
    internshipSupport: true,
  },
  dataSources: {
    source: 'UGC Bangladesh, EWU Official Website',
    lastUpdated: 'June 2026',
    verified: true,
  },
  description: 'East West University (EWU) is a well-established private university offering quality education at a reasonable cost.',
  campusImages: [
    'https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
};

const diu: University = {
  id: 'diu',
  slug: 'daffodil-international-university',
  name: 'Daffodil International University',
  shortName: 'DIU',
  logoColor: '#ca8a04',
  established: 2002,
  ugcApproved: true,
  type: 'Private',
  permanentCampus: true,
  city: 'Dhaka',
  address: '1021 Sukrabad, Daffodil Tower, Dhanmondi, Dhaka-1207',
  website: 'https://www.daffodilvarsity.edu.bd',
  phone: '+880 2 9660123',
  email: 'info@daffodilvarsity.edu.bd',
  viceChancellor: 'Prof. Dr. M. Lutfar Rahman',
  students: 18000,
  faculty: 600,
  campusArea: 'Dhanmondi Campus + Ashulia Permanent Campus',
  semesterSystem: 'Semester (3 per year)',
  iebAccredited: false,
  iebDepartments: [],
  ranking: 7,
  qsRanking: 'Not ranked',
  tuitionRange: [2500, 4500],
  hasHostel: true,
  hasTransport: true,
  hasScholarship: true,
  socialLinks: { facebook: 'https://facebook.com/daffodilvarsity' },
  programs: [
    makeProgram('diu-cse', 'BSc in Computer Science & Engineering', 'BSc', 'Engineering', 144, '4 Years', 4000, 15000, 8000),
    makeProgram('diu-eee', 'BSc in Electrical & Electronic Engineering', 'BSc', 'Engineering', 144, '4 Years', 4000, 15000, 8000),
    makeProgram('diu-bba', 'Bachelor of Business Administration', 'BBA', 'Business', 120, '4 Years', 3000, 12000, 3000),
    makeProgram('diu-arch', 'Bachelor of Architecture', 'B.Arch', 'Architecture', 172, '5 Years', 4000, 15000, 8000),
    makeProgram('diu-soft', 'BSc in Software Engineering', 'BSc', 'Engineering', 144, '4 Years', 4000, 15000, 8000),
  ],
  scholarships: standardScholarships,
  reviews: [
    makeReview('r1', 'Mizan R.', 4, 'DIU has a large campus and good tech facilities. The IT programs are strong.'),
    makeReview('r2', 'Lamia H.', 3, 'Affordable tuition but the campus is far from the city center.'),
  ],
  facilities: [...standardFacilities, 'Innovation Center', 'Research Labs', 'Gym'],
  clubs: [...standardClubs, 'IEEE Student Branch', 'ACM Student Chapter', 'Entrepreneurship Club'],
  careerStats: {
    employmentRate: 82,
    topRecruiters: ['Daffodil Software', 'Brain Station 23', 'Reve Systems', 'Kazi IT'],
    averageSalary: 'BDT 30,000–45,000/month',
    internshipSupport: true,
  },
  dataSources: {
    source: 'UGC Bangladesh, DIU Official Website',
    lastUpdated: 'June 2026',
    verified: true,
  },
  description: 'Daffodil International University (DIU) is a large private university with a focus on IT and technology education.',
  campusImages: [
    'https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
};

const iubat: University = {
  id: 'iubat',
  slug: 'iubat',
  name: 'International University of Business Agriculture and Technology',
  shortName: 'IUBAT',
  logoColor: '#7c3aed',
  established: 1991,
  ugcApproved: true,
  type: 'Private',
  permanentCampus: true,
  city: 'Dhaka',
  address: '4 Embankment Drive Road, Sector 10, Uttara Model Town, Dhaka-1230',
  website: 'https://www.iubat.edu',
  phone: '+880 2 8030538',
  email: 'info@iubat.edu',
  viceChancellor: 'Prof. Dr. Abdur Rab',
  students: 7000,
  faculty: 300,
  campusArea: 'Uttara Campus',
  semesterSystem: 'Semester (3 per year)',
  iebAccredited: false,
  iebDepartments: [],
  ranking: 8,
  qsRanking: 'Not ranked',
  tuitionRange: [3000, 5000],
  hasHostel: true,
  hasTransport: true,
  hasScholarship: true,
  socialLinks: { facebook: 'https://facebook.com/iubat.edu' },
  programs: [
    makeProgram('iubat-cse', 'BSc in Computer Science & Engineering', 'BSc', 'Engineering', 150, '4 Years', 4500, 15000, 8000),
    makeProgram('iubat-eee', 'BSc in Electrical & Electronic Engineering', 'BSc', 'Engineering', 150, '4 Years', 4500, 15000, 8000),
    makeProgram('iubat-bba', 'Bachelor of Business Administration', 'BBA', 'Business', 120, '4 Years', 3500, 12000, 3000),
    makeProgram('iubat-agri', 'BSc in Agriculture', 'BSc', 'Science', 160, '4 Years', 3500, 12000, 5000),
    makeProgram('iubat-nursing', 'BSc in Nursing', 'BSc', 'Medical', 160, '4 Years', 4000, 15000, 8000),
  ],
  scholarships: standardScholarships,
  reviews: [
    makeReview('r1', 'Shahriar M.', 4, 'IUBAT is the first private university in Bangladesh. Good for agriculture and business programs.'),
    makeReview('r2', 'Nusrat J.', 3, 'Decent university with hostel facilities. The Uttara location is convenient.'),
  ],
  facilities: [...standardFacilities, 'Agriculture Farm', 'Research Center'],
  clubs: [...standardClubs, 'Agriculture Club', 'Business Club'],
  careerStats: {
    employmentRate: 80,
    topRecruiters: ['BRAC', 'ACI', 'Beximco', 'Pran-RFL'],
    averageSalary: 'BDT 30,000–40,000/month',
    internshipSupport: true,
  },
  dataSources: {
    source: 'UGC Bangladesh, IUBAT Official Website',
    lastUpdated: 'June 2026',
    verified: true,
  },
  description: 'IUBAT is the first private university in Bangladesh, offering unique programs in agriculture, business, and technology.',
  campusImages: [
    'https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
};

const uap: University = {
  id: 'uap',
  slug: 'university-of-asia-pacific',
  name: 'University of Asia Pacific',
  shortName: 'UAP',
  logoColor: '#0891b2',
  established: 1996,
  ugcApproved: true,
  type: 'Private',
  permanentCampus: false,
  city: 'Dhaka',
  address: 'House 73, Road 5A, Dhanmondi, Dhaka-1209',
  website: 'https://www.uap-bd.edu',
  phone: '+880 2 9671230',
  email: 'info@uap-bd.edu',
  viceChancellor: 'Prof. Dr. Qumrul Hoda',
  students: 6000,
  faculty: 250,
  campusArea: 'Dhanmondi Campus',
  semesterSystem: 'Semester (3 per year)',
  iebAccredited: true,
  iebDepartments: ['CSE', 'CE', 'EEE'],
  ranking: 9,
  qsRanking: 'Not ranked',
  tuitionRange: [3500, 5500],
  hasHostel: false,
  hasTransport: true,
  hasScholarship: true,
  socialLinks: { facebook: 'https://facebook.com/uapbd' },
  programs: [
    makeProgram('uap-cse', 'BSc in Computer Science & Engineering', 'BSc', 'Engineering', 150, '4 Years', 5000, 18000, 10000),
    makeProgram('uap-ce', 'BSc in Civil Engineering', 'BSc', 'Engineering', 150, '4 Years', 5000, 18000, 10000),
    makeProgram('uap-eee', 'BSc in Electrical & Electronic Engineering', 'BSc', 'Engineering', 150, '4 Years', 5000, 18000, 10000),
    makeProgram('uap-arch', 'Bachelor of Architecture', 'B.Arch', 'Architecture', 180, '5 Years', 5000, 18000, 10000),
    makeProgram('uap-bba', 'Bachelor of Business Administration', 'BBA', 'Business', 120, '4 Years', 4000, 15000, 3000),
  ],
  scholarships: standardScholarships,
  reviews: [
    makeReview('r1', 'Tareq A.', 4, 'UAP has strong engineering programs with IEB accreditation. Good value for money.'),
    makeReview('r2', 'Mitu S.', 4, 'Great architecture program. The Dhanmondi location is very convenient.'),
  ],
  facilities: [...standardFacilities, 'Research Labs'],
  clubs: [...standardClubs, 'IEEE Student Branch'],
  careerStats: {
    employmentRate: 86,
    topRecruiters: ['Brain Station 23', 'Samsung R&D', 'Toma Group', 'BRAC'],
    averageSalary: 'BDT 35,000–50,000/month',
    internshipSupport: true,
  },
  dataSources: {
    source: 'UGC Bangladesh, UAP Official Website',
    lastUpdated: 'June 2026',
    verified: true,
  },
  description: 'University of Asia Pacific (UAP) is known for its IEB-accredited engineering and architecture programs.',
  campusImages: [
    'https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
};

const ulab: University = {
  id: 'ulab',
  slug: 'ulab',
  name: 'University of Liberal Arts Bangladesh',
  shortName: 'ULAB',
  logoColor: '#be185d',
  established: 2004,
  ugcApproved: true,
  type: 'Private',
  permanentCampus: false,
  city: 'Dhaka',
  address: 'House 56, Road 4A, Dhanmondi, Dhaka-1209',
  website: 'https://www.ulab.edu.bd',
  phone: '+880 2 9670378',
  email: 'info@ulab.edu.bd',
  viceChancellor: 'Prof. Imran Rahman',
  students: 4000,
  faculty: 200,
  campusArea: 'Dhanmondi Campus',
  semesterSystem: 'Semester (3 per year)',
  iebAccredited: false,
  iebDepartments: [],
  ranking: 10,
  qsRanking: 'Not ranked',
  tuitionRange: [4000, 6000],
  hasHostel: false,
  hasTransport: true,
  hasScholarship: true,
  socialLinks: { facebook: 'https://facebook.com/ULAB.Official' },
  programs: [
    makeProgram('ulab-cse', 'BSc in Computer Science & Engineering', 'BSc', 'Engineering', 136, '4 Years', 5500, 20000, 8000),
    makeProgram('ulab-bba', 'Bachelor of Business Administration', 'BBA', 'Business', 120, '4 Years', 5000, 18000, 3000),
    makeProgram('ulab-english', 'BA in English', 'BA', 'Arts', 120, '4 Years', 4500, 18000, 2000),
    makeProgram('ulab-media', 'BA in Media Studies and Journalism', 'BA', 'Arts', 120, '4 Years', 5000, 18000, 3000),
  ],
  scholarships: standardScholarships,
  reviews: [
    makeReview('r1', 'Papia R.', 4, 'ULAB is great for liberal arts and media studies. Small class sizes and good faculty.'),
    makeReview('r2', 'Sajid K.', 4, 'Good university for those interested in media, journalism, and English.'),
  ],
  facilities: [...standardFacilities, 'Media Lab', 'Research Center'],
  clubs: [...standardClubs, 'Media Club', 'Film Society', 'Literature Club'],
  careerStats: {
    employmentRate: 83,
    topRecruiters: ['Prothom Alo', 'Daily Star', 'Somoy TV', 'BBC Bangla'],
    averageSalary: 'BDT 30,000–45,000/month',
    internshipSupport: true,
  },
  dataSources: {
    source: 'UGC Bangladesh, ULAB Official Website',
    lastUpdated: 'June 2026',
    verified: true,
  },
  description: 'ULAB is a liberal arts-focused university known for its media studies, English, and journalism programs.',
  campusImages: [
    'https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
};

const buet2: University = {
  id: 'bubt',
  slug: 'bangladesh-university-of-business-and-technology',
  name: 'Bangladesh University of Business and Technology',
  shortName: 'BUBT',
  logoColor: '#1e3a8a',
  established: 2003,
  ugcApproved: true,
  type: 'Private',
  permanentCampus: true,
  city: 'Dhaka',
  address: 'Rupnagar R/A, Mirpur, Dhaka-1216',
  website: 'https://www.bubt.edu.bd',
  phone: '+880 2 8033091',
  email: 'info@bubt.edu.bd',
  viceChancellor: 'Prof. Dr. Md. Ali Ashraf',
  students: 8000,
  faculty: 300,
  campusArea: 'Mirpur Campus',
  semesterSystem: 'Semester (3 per year)',
  iebAccredited: false,
  iebDepartments: [],
  ranking: 11,
  qsRanking: 'Not ranked',
  tuitionRange: [2500, 4000],
  hasHostel: true,
  hasTransport: true,
  hasScholarship: true,
  socialLinks: { facebook: 'https://facebook.com/bubt.edu.bd' },
  programs: [
    makeProgram('bubt-cse', 'BSc in Computer Science & Engineering', 'BSc', 'Engineering', 150, '4 Years', 3500, 12000, 6000),
    makeProgram('bubt-eee', 'BSc in Electrical & Electronic Engineering', 'BSc', 'Engineering', 150, '4 Years', 3500, 12000, 6000),
    makeProgram('bubt-bba', 'Bachelor of Business Administration', 'BBA', 'Business', 120, '4 Years', 2500, 10000, 2000),
    makeProgram('bubt-eco', 'BSc in Economics', 'BSc', 'Science', 120, '4 Years', 2500, 10000, 2000),
    makeProgram('bubt-english', 'BA in English', 'BA', 'Arts', 120, '4 Years', 2500, 10000, 2000),
  ],
  scholarships: standardScholarships,
  reviews: [
    makeReview('r1', 'Rakib H.', 4, 'BUBT is affordable and has a good business school. The Mirpur campus is spacious.'),
    makeReview('r2', 'Shila A.', 3, 'Reasonable tuition with hostel facilities. Faculty could be better in some departments.'),
  ],
  facilities: [...standardFacilities, 'Research Center'],
  clubs: [...standardClubs, 'Business Club', 'Debate Club'],
  careerStats: {
    employmentRate: 78,
    topRecruiters: ['BRAC', 'Beximco', 'City Bank', 'BRAC Bank'],
    averageSalary: 'BDT 25,000–40,000/month',
    internshipSupport: true,
  },
  dataSources: {
    source: 'UGC Bangladesh, BUBT Official Website',
    lastUpdated: 'June 2026',
    verified: true,
  },
  description: 'BUBT is an affordable private university with a strong focus on business and technology education.',
  campusImages: [
    'https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
};

const green: University = {
  id: 'gub',
  slug: 'green-university-of-bangladesh',
  name: 'Green University of Bangladesh',
  shortName: 'GUB',
  logoColor: '#16a34a',
  established: 2003,
  ugcApproved: true,
  type: 'Private',
  permanentCampus: true,
  city: 'Dhaka',
  address: '220/D, Begum Rokeya Sarani, Green Tower, Dhaka-1207',
  website: 'https://www.green.edu.bd',
  phone: '+880 2 8032046',
  email: 'info@green.edu.bd',
  viceChancellor: 'Prof. Dr. Md. Fayzur Rahman',
  students: 9000,
  faculty: 350,
  campusArea: 'Green Tower Campus',
  semesterSystem: 'Semester (3 per year)',
  iebAccredited: false,
  iebDepartments: [],
  ranking: 12,
  qsRanking: 'Not ranked',
  tuitionRange: [2500, 4500],
  hasHostel: true,
  hasTransport: true,
  hasScholarship: true,
  socialLinks: { facebook: 'https://facebook.com/greenuniversitybd' },
  programs: [
    makeProgram('gub-cse', 'BSc in Computer Science & Engineering', 'BSc', 'Engineering', 144, '4 Years', 4000, 12000, 6000),
    makeProgram('gub-eee', 'BSc in Electrical & Electronic Engineering', 'BSc', 'Engineering', 144, '4 Years', 4000, 12000, 6000),
    makeProgram('gub-bba', 'Bachelor of Business Administration', 'BBA', 'Business', 120, '4 Years', 3000, 10000, 2000),
    makeProgram('gub-english', 'BA in English', 'BA', 'Arts', 120, '4 Years', 2500, 10000, 2000),
  ],
  scholarships: standardScholarships,
  reviews: [
    makeReview('r1', 'Naimur R.', 4, 'GUB has good facilities and affordable tuition. The CSE department is growing.'),
    makeReview('r2', 'Farzana H.', 3, 'Decent university with hostel facilities. Some departments need improvement.'),
  ],
  facilities: [...standardFacilities, 'Research Labs', 'Innovation Center'],
  clubs: [...standardClubs, 'IEEE Student Branch', 'Business Club'],
  careerStats: {
    employmentRate: 79,
    topRecruiters: ['Brain Station 23', 'BRAC', 'Grameenphone', 'Beximco'],
    averageSalary: 'BDT 28,000–42,000/month',
    internshipSupport: true,
  },
  dataSources: {
    source: 'UGC Bangladesh, GUB Official Website',
    lastUpdated: 'June 2026',
    verified: true,
  },
  description: 'Green University of Bangladesh (GUB) offers affordable education with modern facilities.',
  campusImages: [
    'https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
};

const stamford: University = {
  id: 'stamford',
  slug: 'stamford-university-bangladesh',
  name: 'Stamford University Bangladesh',
  shortName: 'STAMFORD',
  logoColor: '#9333ea',
  established: 2002,
  ugcApproved: true,
  type: 'Private',
  permanentCampus: true,
  city: 'Dhaka',
  address: '66 Siddeswari Road, Dhaka-1217',
  website: 'https://www.stamforduniversity.edu.bd',
  phone: '+880 2 8365663',
  email: 'info@stamforduniversity.edu.bd',
  viceChancellor: 'Prof. Dr. M. Moniruzzaman',
  students: 15000,
  faculty: 500,
  campusArea: 'Siddeswari Campus',
  semesterSystem: 'Semester (3 per year)',
  iebAccredited: false,
  iebDepartments: [],
  ranking: 13,
  qsRanking: 'Not ranked',
  tuitionRange: [2000, 4000],
  hasHostel: true,
  hasTransport: true,
  hasScholarship: true,
  socialLinks: { facebook: 'https://facebook.com/stamforduniversitybd' },
  programs: [
    makeProgram('stam-cse', 'BSc in Computer Science & Engineering', 'BSc', 'Engineering', 144, '4 Years', 3500, 10000, 5000),
    makeProgram('stam-eee', 'BSc in Electrical & Electronic Engineering', 'BSc', 'Engineering', 144, '4 Years', 3500, 10000, 5000),
    makeProgram('stam-bba', 'Bachelor of Business Administration', 'BBA', 'Business', 120, '4 Years', 2500, 8000, 2000),
    makeProgram('stam-arch', 'Bachelor of Architecture', 'B.Arch', 'Architecture', 172, '5 Years', 3500, 10000, 5000),
    makeProgram('stam-pharmacy', 'BPharm', 'BPharm', 'Medical', 160, '4 Years', 4000, 12000, 8000),
  ],
  scholarships: standardScholarships,
  reviews: [
    makeReview('r1', 'Jubayer A.', 3, 'Stamford is one of the most affordable private universities. Good for budget-conscious students.'),
    makeReview('r2', 'Mim K.', 3, 'Affordable but class sizes can be large. The pharmacy program is decent.'),
  ],
  facilities: [...standardFacilities, 'Pharmacy Lab', 'Research Center'],
  clubs: [...standardClubs, 'Pharmacy Club', 'Business Club'],
  careerStats: {
    employmentRate: 75,
    topRecruiters: ['Square Pharma', 'Beximco Pharma', 'BRAC', 'City Bank'],
    averageSalary: 'BDT 25,000–38,000/month',
    internshipSupport: true,
  },
  dataSources: {
    source: 'UGC Bangladesh, Stamford University Official Website',
    lastUpdated: 'June 2026',
    verified: true,
  },
  description: 'Stamford University Bangladesh is one of the most affordable private universities with a wide range of programs.',
  campusImages: [
    'https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
};

const southeast: University = {
  id: 'southeast',
  slug: 'southeast-university',
  name: 'Southeast University',
  shortName: 'SEU',
  logoColor: '#0d9488',
  established: 2002,
  ugcApproved: true,
  type: 'Private',
  permanentCampus: false,
  city: 'Dhaka',
  address: 'House 64, Road 18, Block B, Banani, Dhaka-1213',
  website: 'https://www.seu.edu.bd',
  phone: '+880 2 9889336',
  email: 'info@seu.ac.bd',
  viceChancellor: 'Prof. Dr. ANM Mosharraf Hossain',
  students: 10000,
  faculty: 400,
  campusArea: 'Banani Campus',
  semesterSystem: 'Semester (3 per year)',
  iebAccredited: false,
  iebDepartments: [],
  ranking: 14,
  qsRanking: 'Not ranked',
  tuitionRange: [2500, 4500],
  hasHostel: false,
  hasTransport: true,
  hasScholarship: true,
  socialLinks: { facebook: 'https://facebook.com/seubd' },
  programs: [
    makeProgram('seu-cse', 'BSc in Computer Science & Engineering', 'BSc', 'Engineering', 144, '4 Years', 4000, 12000, 6000),
    makeProgram('seu-eee', 'BSc in Electrical & Electronic Engineering', 'BSc', 'Engineering', 144, '4 Years', 4000, 12000, 6000),
    makeProgram('seu-bba', 'Bachelor of Business Administration', 'BBA', 'Business', 120, '4 Years', 3000, 10000, 2000),
    makeProgram('seu-arch', 'Bachelor of Architecture', 'B.Arch', 'Architecture', 172, '5 Years', 4000, 12000, 6000),
    makeProgram('seu-english', 'BA in English', 'BA', 'Arts', 120, '4 Years', 2500, 10000, 2000),
  ],
  scholarships: standardScholarships,
  reviews: [
    makeReview('r1', 'Sabbir R.', 4, 'SEU has a good location in Banani and reasonable tuition. The CSE program is solid.'),
    makeReview('r2', 'Tania A.', 3, 'Good university but no permanent campus yet. Faculty is mixed.'),
  ],
  facilities: [...standardFacilities, 'Research Labs'],
  clubs: [...standardClubs, 'Business Club', 'Cultural Club'],
  careerStats: {
    employmentRate: 80,
    topRecruiters: ['BRAC', 'Grameenphone', 'Brain Station 23', 'Beximco'],
    averageSalary: 'BDT 28,000–42,000/month',
    internshipSupport: true,
  },
  dataSources: {
    source: 'UGC Bangladesh, SEU Official Website',
    lastUpdated: 'June 2026',
    verified: true,
  },
  description: 'Southeast University (SEU) offers affordable education in a convenient Banani location.',
  campusImages: [
    'https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
};

const iiuc: University = {
  id: 'iiuc',
  slug: 'international-islamic-university-chittagong',
  name: 'International Islamic University Chittagong',
  shortName: 'IIUC',
  logoColor: '#15803d',
  established: 1999,
  ugcApproved: true,
  type: 'Private',
  permanentCampus: true,
  city: 'Chittagong',
  address: '154-155, College Road, Chawkbazar, Chittagong-4203',
  website: 'https://www.iiuc.ac.bd',
  phone: '+880 31 2850147',
  email: 'info@iiuc.ac.bd',
  viceChancellor: 'Prof. Dr. A.K.M. Nurul Haque',
  students: 12000,
  faculty: 450,
  campusArea: 'Chawkbazar Campus',
  semesterSystem: 'Semester (3 per year)',
  iebAccredited: false,
  iebDepartments: [],
  ranking: 15,
  qsRanking: 'Not ranked',
  tuitionRange: [2000, 4000],
  hasHostel: true,
  hasTransport: true,
  hasScholarship: true,
  socialLinks: { facebook: 'https://facebook.com/iiuc.ac.bd' },
  programs: [
    makeProgram('iiuc-cse', 'BSc in Computer Science & Engineering', 'BSc', 'Engineering', 144, '4 Years', 3500, 10000, 5000),
    makeProgram('iiuc-eee', 'BSc in Electrical & Electronic Engineering', 'BSc', 'Engineering', 144, '4 Years', 3500, 10000, 5000),
    makeProgram('iiuc-bba', 'Bachelor of Business Administration', 'BBA', 'Business', 120, '4 Years', 2500, 8000, 2000),
    makeProgram('iiuc-english', 'BA in English', 'BA', 'Arts', 120, '4 Years', 2000, 8000, 2000),
    makeProgram('iiuc-islamic', 'BA in Islamic Studies', 'BA', 'Arts', 120, '4 Years', 2000, 8000, 1000),
  ],
  scholarships: standardScholarships,
  reviews: [
    makeReview('r1', 'Omar F.', 4, 'IIUC is the best private university in Chittagong. Good Islamic values combined with modern education.'),
    makeReview('r2', 'Ayesha K.', 4, 'Great university with hostel facilities. The campus is well-maintained.'),
  ],
  facilities: [...standardFacilities, 'Mosque', 'Research Center', 'Library (Large)'],
  clubs: [...standardClubs, 'Islamic Club', 'Debate Club', 'Business Club'],
  careerStats: {
    employmentRate: 82,
    topRecruiters: ['BRAC', 'Grameenphone', 'City Bank', 'Pran-RFL'],
    averageSalary: 'BDT 28,000–40,000/month',
    internshipSupport: true,
  },
  dataSources: {
    source: 'UGC Bangladesh, IIUC Official Website',
    lastUpdated: 'June 2026',
    verified: true,
  },
  description: 'IIUC is the leading private university in Chittagong, combining Islamic values with modern education.',
  campusImages: [
    'https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
};

const ciu: University = {
  id: 'ciu',
  slug: 'chittagong-independent-university',
  name: 'Chittagong Independent University',
  shortName: 'CIU',
  logoColor: '#1d4ed8',
  established: 1999,
  ugcApproved: true,
  type: 'Private',
  permanentCampus: true,
  city: 'Chittagong',
  address: ' Jamal Khan, Chittagong-4000',
  website: 'https://www.ciu.edu.bd',
  phone: '+880 31 611392',
  email: 'info@ciu.edu.bd',
  viceChancellor: 'Prof. Dr. Mahfuzul Hoque',
  students: 4000,
  faculty: 150,
  campusArea: ' Jamal Khan Campus',
  semesterSystem: 'Semester (3 per year)',
  iebAccredited: false,
  iebDepartments: [],
  ranking: 16,
  qsRanking: 'Not ranked',
  tuitionRange: [3000, 5000],
  hasHostel: false,
  hasTransport: true,
  hasScholarship: true,
  socialLinks: { facebook: 'https://facebook.com/ciu.edu.bd' },
  programs: [
    makeProgram('ciu-cse', 'BSc in Computer Science & Engineering', 'BSc', 'Engineering', 144, '4 Years', 4500, 12000, 6000),
    makeProgram('ciu-bba', 'Bachelor of Business Administration', 'BBA', 'Business', 120, '4 Years', 3500, 10000, 2000),
    makeProgram('ciu-english', 'BA in English', 'BA', 'Arts', 120, '4 Years', 3000, 10000, 2000),
  ],
  scholarships: standardScholarships,
  reviews: [
    makeReview('r1', 'Rashed C.', 4, 'CIU is a good option in Chittagong. Small class sizes and personal attention from faculty.'),
  ],
  facilities: [...standardFacilities, 'Research Center'],
  clubs: [...standardClubs, 'Business Club', 'Cultural Club'],
  careerStats: {
    employmentRate: 78,
    topRecruiters: ['BRAC', 'City Bank', 'Beximco', 'Pran-RFL'],
    averageSalary: 'BDT 25,000–38,000/month',
    internshipSupport: true,
  },
  dataSources: {
    source: 'UGC Bangladesh, CIU Official Website',
    lastUpdated: 'June 2026',
    verified: true,
  },
  description: 'Chittagong Independent University (CIU) is a growing private university in the port city.',
  campusImages: [
    'https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
};

const detailedUniversities: University[] = [
  buet, brac, nsu, iub, aiub, ewu, diu, iubat, uap, ulab, buet2, green, stamford, southeast, iiuc, ciu,
];

// ── Lighter data for remaining universities ────────────────────────

interface LightUni {
  name: string;
  shortName: string;
  established: number;
  city: string;
  tuitionRange: [number, number];
  ieb: boolean;
  permanentCampus: boolean;
  hasHostel: boolean;
  ranking: number;
}

const lightUnis: LightUni[] = [
  { name: 'Anwer Khan Modern University', shortName: 'AKMU', established: 2012, city: 'Dhaka', tuitionRange: [2000, 3500], ieb: false, permanentCampus: false, hasHostel: false, ranking: 50 },
  { name: 'ASA University Bangladesh', shortName: 'ASAUB', established: 2006, city: 'Dhaka', tuitionRange: [2000, 3500], ieb: false, permanentCampus: false, hasHostel: false, ranking: 40 },
  { name: 'Asian University of Bangladesh', shortName: 'AUB', established: 1996, city: 'Dhaka', tuitionRange: [1500, 3000], ieb: false, permanentCampus: true, hasHostel: true, ranking: 45 },
  { name: 'Atish Dipankar University of Science & Technology', shortName: 'ADUST', established: 2012, city: 'Dhaka', tuitionRange: [2000, 3500], ieb: false, permanentCampus: false, hasHostel: false, ranking: 55 },
  { name: 'Bandarban University', shortName: 'BU', established: 2015, city: 'Bandarban', tuitionRange: [1500, 2500], ieb: false, permanentCampus: false, hasHostel: true, ranking: 70 },
  { name: 'Bangladesh Army International University of Science and Technology', shortName: 'BAIUST', established: 2015, city: 'Comilla', tuitionRange: [3000, 5000], ieb: false, permanentCampus: true, hasHostel: true, ranking: 30 },
  { name: 'Bangladesh Army University of Engineering & Technology', shortName: 'BAUET', established: 2015, city: 'Natore', tuitionRange: [3000, 5000], ieb: true, permanentCampus: true, hasHostel: true, ranking: 25 },
  { name: 'Bangladesh Army University of Science and Technology', shortName: 'BAUST', established: 2015, city: 'Saidpur', tuitionRange: [3000, 5000], ieb: false, permanentCampus: true, hasHostel: true, ranking: 35 },
  { name: 'Bangladesh Islami University', shortName: 'BIU', established: 2006, city: 'Dhaka', tuitionRange: [1500, 3000], ieb: false, permanentCampus: false, hasHostel: false, ranking: 60 },
  { name: 'Bangladesh University', shortName: 'BU', established: 2001, city: 'Dhaka', tuitionRange: [2000, 3500], ieb: false, permanentCampus: false, hasHostel: false, ranking: 50 },
  { name: 'Bangladesh University of Health Sciences', shortName: 'BUHS', established: 2012, city: 'Dhaka', tuitionRange: [4000, 6000], ieb: false, permanentCampus: false, hasHostel: false, ranking: 45 },
  { name: 'BGC Trust University Bangladesh', shortName: 'BGCTUB', established: 2001, city: 'Chittagong', tuitionRange: [2000, 3500], ieb: false, permanentCampus: true, hasHostel: true, ranking: 55 },
  { name: 'BGMEA University of Fashion & Technology', shortName: 'BUFT', established: 2012, city: 'Dhaka', tuitionRange: [3000, 5000], ieb: false, permanentCampus: true, hasHostel: false, ranking: 40 },
  { name: 'Britannia University', shortName: 'BU', established: 2012, city: 'Comilla', tuitionRange: [1500, 2500], ieb: false, permanentCampus: false, hasHostel: false, ranking: 65 },
  { name: 'Canadian University of Bangladesh', shortName: 'CUB', established: 2015, city: 'Dhaka', tuitionRange: [3000, 5000], ieb: false, permanentCampus: false, hasHostel: false, ranking: 45 },
  { name: 'CCN University of Science & Technology', shortName: 'CCNUST', established: 2014, city: 'Khulna', tuitionRange: [1500, 2500], ieb: false, permanentCampus: false, hasHostel: true, ranking: 65 },
  { name: 'Central Women\'s University', shortName: 'CWU', established: 1993, city: 'Dhaka', tuitionRange: [2000, 3500], ieb: false, permanentCampus: false, hasHostel: false, ranking: 60 },
  { name: 'City University', shortName: 'CU', established: 2002, city: 'Dhaka', tuitionRange: [2000, 3500], ieb: false, permanentCampus: false, hasHostel: false, ranking: 45 },
  { name: 'Cox\'s Bazar International University', shortName: 'CBIU', established: 2014, city: 'Cox\'s Bazar', tuitionRange: [2000, 3500], ieb: false, permanentCampus: false, hasHostel: true, ranking: 60 },
  { name: 'Dhaka International University', shortName: 'DIU', established: 1995, city: 'Dhaka', tuitionRange: [2500, 4000], ieb: false, permanentCampus: false, hasHostel: false, ranking: 40 },
  { name: 'East Delta University', shortName: 'EDU', established: 2006, city: 'Chittagong', tuitionRange: [3000, 5000], ieb: false, permanentCampus: true, hasHostel: false, ranking: 35 },
  { name: 'Eastern University', shortName: 'EU', established: 2003, city: 'Dhaka', tuitionRange: [2500, 4000], ieb: false, permanentCampus: false, hasHostel: false, ranking: 40 },
  { name: 'Exim Bank Agricultural University Bangladesh', shortName: 'EBAUB', established: 2013, city: 'Narayanganj', tuitionRange: [2500, 4000], ieb: false, permanentCampus: true, hasHostel: true, ranking: 45 },
  { name: 'Fareast International University', shortName: 'FIU', established: 2012, city: 'Dhaka', tuitionRange: [2000, 3500], ieb: false, permanentCampus: false, hasHostel: false, ranking: 55 },
  { name: 'First Capital University of Bangladesh', shortName: 'FCUB', established: 2012, city: 'Comilla', tuitionRange: [1500, 2500], ieb: false, permanentCampus: false, hasHostel: false, ranking: 65 },
  { name: 'German University Bangladesh', shortName: 'GUB', established: 2015, city: 'Dhaka', tuitionRange: [4000, 6000], ieb: false, permanentCampus: false, hasHostel: false, ranking: 50 },
  { name: 'Global University Bangladesh', shortName: 'GUB', established: 2012, city: 'Bogura', tuitionRange: [1500, 2500], ieb: false, permanentCampus: false, hasHostel: true, ranking: 65 },
  { name: 'Gono Bishwabidyalay', shortName: 'GB', established: 1998, city: 'Dhaka', tuitionRange: [1500, 3000], ieb: false, permanentCampus: true, hasHostel: true, ranking: 50 },
  { name: 'Hamdard University Bangladesh', shortName: 'HUB', established: 2012, city: 'Dhaka', tuitionRange: [2000, 3500], ieb: false, permanentCampus: false, hasHostel: false, ranking: 55 },
  { name: 'Ishakha International University', shortName: 'IIU', established: 2014, city: 'Narayanganj', tuitionRange: [2000, 3500], ieb: false, permanentCampus: false, hasHostel: false, ranking: 60 },
  { name: 'Khwaja Yunus Ali University', shortName: 'KYAU', established: 2012, city: 'Natore', tuitionRange: [2000, 3500], ieb: false, permanentCampus: true, hasHostel: true, ranking: 55 },
  { name: 'Leading University', shortName: 'LU', established: 2001, city: 'Sylhet', tuitionRange: [2500, 4000], ieb: false, permanentCampus: true, hasHostel: true, ranking: 40 },
  { name: 'Manarat International University', shortName: 'MIU', established: 2001, city: 'Dhaka', tuitionRange: [3000, 5000], ieb: false, permanentCampus: true, hasHostel: true, ranking: 35 },
  { name: 'Metropolitan University', shortName: 'MU', established: 2003, city: 'Sylhet', tuitionRange: [2000, 3500], ieb: false, permanentCampus: true, hasHostel: false, ranking: 45 },
  { name: 'Millennium University', shortName: 'TMU', established: 2003, city: 'Dhaka', tuitionRange: [2000, 3500], ieb: false, permanentCampus: false, hasHostel: false, ranking: 60 },
  { name: 'North Bengal International University', shortName: 'NBIU', established: 2012, city: 'Rajshahi', tuitionRange: [1500, 2500], ieb: false, permanentCampus: false, hasHostel: true, ranking: 60 },
  { name: 'North East University Bangladesh', shortName: 'NEUB', established: 2012, city: 'Sylhet', tuitionRange: [2000, 3500], ieb: false, permanentCampus: false, hasHostel: true, ranking: 50 },
  { name: 'Northern University Bangladesh', shortName: 'NUB', established: 2002, city: 'Dhaka', tuitionRange: [2500, 4000], ieb: false, permanentCampus: true, hasHostel: false, ranking: 40 },
  { name: 'Notre Dame University Bangladesh', shortName: 'NDUB', established: 2013, city: 'Dhaka', tuitionRange: [2000, 3500], ieb: false, permanentCampus: false, hasHostel: false, ranking: 45 },
  { name: 'Port City International University', shortName: 'PCIU', established: 2012, city: 'Chittagong', tuitionRange: [2000, 3500], ieb: false, permanentCampus: true, hasHostel: true, ranking: 50 },
  { name: 'Premier University', shortName: 'PU', established: 2001, city: 'Chittagong', tuitionRange: [2000, 3500], ieb: false, permanentCampus: true, hasHostel: false, ranking: 45 },
  { name: 'Presidency University', shortName: 'PU', established: 2003, city: 'Dhaka', tuitionRange: [3000, 5000], ieb: false, permanentCampus: false, hasHostel: false, ranking: 40 },
  { name: 'Prime University', shortName: 'PU', established: 2002, city: 'Dhaka', tuitionRange: [2000, 3500], ieb: false, permanentCampus: false, hasHostel: false, ranking: 50 },
  { name: 'Primeasia University', shortName: 'PAU', established: 2003, city: 'Dhaka', tuitionRange: [2500, 4000], ieb: false, permanentCampus: false, hasHostel: false, ranking: 45 },
  { name: 'Pundra University of Science & Technology', shortName: 'PUST', established: 2012, city: 'Bogura', tuitionRange: [2000, 3500], ieb: false, permanentCampus: true, hasHostel: true, ranking: 55 },
  { name: 'Queens University', shortName: 'QU', established: 1996, city: 'Dhaka', tuitionRange: [2000, 3500], ieb: false, permanentCampus: false, hasHostel: false, ranking: 55 },
  { name: 'Rabindra Maitree University', shortName: 'RMU', established: 2015, city: 'Khulna', tuitionRange: [1500, 2500], ieb: false, permanentCampus: false, hasHostel: true, ranking: 65 },
  { name: 'Ranada Prasad Shaha University', shortName: 'RPSU', established: 2014, city: 'Narayanganj', tuitionRange: [2000, 3500], ieb: false, permanentCampus: false, hasHostel: false, ranking: 60 },
  { name: 'Royal University of Dhaka', shortName: 'RUD', established: 2003, city: 'Dhaka', tuitionRange: [2000, 3500], ieb: false, permanentCampus: false, hasHostel: false, ranking: 55 },
  { name: 'Shanto-Mariam University of Creative Technology', shortName: 'SMUCT', established: 2010, city: 'Dhaka', tuitionRange: [3000, 5000], ieb: false, permanentCampus: true, hasHostel: false, ranking: 50 },
  { name: 'Sheikh Fazilatunnesa Mujib University', shortName: 'SFMU', established: 2015, city: 'Dhaka', tuitionRange: [2000, 3500], ieb: false, permanentCampus: false, hasHostel: false, ranking: 60 },
  { name: 'Sonargaon University', shortName: 'SU', established: 2012, city: 'Dhaka', tuitionRange: [2500, 4000], ieb: false, permanentCampus: false, hasHostel: false, ranking: 45 },
  { name: 'Southern University Bangladesh', shortName: 'SUB', established: 2002, city: 'Chittagong', tuitionRange: [2500, 4000], ieb: false, permanentCampus: true, hasHostel: true, ranking: 40 },
  { name: 'State University of Bangladesh', shortName: 'SUB', established: 2002, city: 'Dhaka', tuitionRange: [2500, 4000], ieb: false, permanentCampus: false, hasHostel: false, ranking: 45 },
  { name: 'Sylhet International University', shortName: 'SIU', established: 2012, city: 'Sylhet', tuitionRange: [2000, 3500], ieb: false, permanentCampus: false, hasHostel: true, ranking: 55 },
  { name: 'Times University Bangladesh', shortName: 'TUB', established: 2013, city: 'Rajshahi', tuitionRange: [1500, 2500], ieb: false, permanentCampus: false, hasHostel: true, ranking: 65 },
  { name: 'University of Development Alternative', shortName: 'UODA', established: 2002, city: 'Dhaka', tuitionRange: [2500, 4000], ieb: false, permanentCampus: false, hasHostel: false, ranking: 50 },
  { name: 'University of Global Village', shortName: 'UGV', established: 2015, city: 'Barishal', tuitionRange: [2000, 3500], ieb: false, permanentCampus: true, hasHostel: true, ranking: 60 },
  { name: 'University of Information Technology & Sciences', shortName: 'UITS', established: 2002, city: 'Dhaka', tuitionRange: [2500, 4000], ieb: false, permanentCampus: true, hasHostel: false, ranking: 45 },
  { name: 'University of Science & Technology Chittagong', shortName: 'USTC', established: 1986, city: 'Chittagong', tuitionRange: [3000, 5000], ieb: false, permanentCampus: true, hasHostel: true, ranking: 35 },
  { name: 'University of South Asia', shortName: 'USA', established: 2003, city: 'Dhaka', tuitionRange: [2000, 3500], ieb: false, permanentCampus: false, hasHostel: false, ranking: 50 },
  { name: 'Uttara University', shortName: 'UU', established: 2002, city: 'Dhaka', tuitionRange: [2000, 3500], ieb: false, permanentCampus: true, hasHostel: false, ranking: 45 },
  { name: 'Varendra University', shortName: 'VU', established: 2012, city: 'Rajshahi', tuitionRange: [2000, 3500], ieb: false, permanentCampus: true, hasHostel: true, ranking: 50 },
  { name: 'Victoria University of Bangladesh', shortName: 'VUB', established: 2003, city: 'Dhaka', tuitionRange: [2500, 4000], ieb: false, permanentCampus: false, hasHostel: false, ranking: 50 },
  { name: 'World University of Bangladesh', shortName: 'WUB', established: 2000, city: 'Dhaka', tuitionRange: [2000, 3500], ieb: false, permanentCampus: true, hasHostel: false, ranking: 45 },
  { name: 'Ahsania Mission University of Science and Technology', shortName: 'AMUST', established: 2018, city: 'Dhaka', tuitionRange: [2000, 3500], ieb: false, permanentCampus: false, hasHostel: false, ranking: 60 },
];

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function lightToFull(l: LightUni): University {
  const slug = slugify(l.name);
  const colors = ['#1e40af', '#b91c1c', '#0f766e', '#7c3aed', '#ca8a04', '#0891b2', '#be185d', '#15803d', '#dc2626', '#1d4ed8'];
  return {
    id: slug,
    slug,
    name: l.name,
    shortName: l.shortName,
    logoColor: colors[Math.floor(Math.random() * colors.length)],
    established: l.established,
    ugcApproved: true,
    type: 'Private',
    permanentCampus: l.permanentCampus,
    city: l.city,
    address: l.city + ', Bangladesh',
    website: 'https://example.edu.bd',
    phone: '+880 2 0000000',
    email: 'info@example.edu.bd',
    viceChancellor: 'To be updated',
    students: Math.floor(2000 + Math.random() * 8000),
    faculty: Math.floor(100 + Math.random() * 300),
    campusArea: 'To be updated',
    semesterSystem: 'Semester (3 per year)',
    iebAccredited: l.ieb,
    iebDepartments: l.ieb ? ['CSE', 'EEE'] : [],
    ranking: l.ranking,
    qsRanking: 'Not ranked',
    tuitionRange: l.tuitionRange,
    hasHostel: l.hasHostel,
    hasTransport: true,
    hasScholarship: true,
    socialLinks: {},
    programs: [
      makeProgram(slug + '-cse', 'BSc in Computer Science & Engineering', 'BSc', 'Engineering', 144, '4 Years', l.tuitionRange[0] + 500, 12000, 6000),
      makeProgram(slug + '-bba', 'Bachelor of Business Administration', 'BBA', 'Business', 120, '4 Years', l.tuitionRange[0], 10000, 2000),
    ],
    scholarships: standardScholarships,
    reviews: [
      makeReview('r1', 'Student Reviewer', 4, 'Information for this university is being compiled. Please check back soon for detailed reviews.'),
    ],
    facilities: standardFacilities,
    clubs: standardClubs,
    careerStats: {
      employmentRate: 75 + Math.floor(Math.random() * 15),
      topRecruiters: ['BRAC', 'Grameenphone', 'Beximco', 'City Bank'],
      averageSalary: 'BDT 25,000–40,000/month',
      internshipSupport: true,
    },
    dataSources: {
      source: 'UGC Bangladesh, University Official Website',
      lastUpdated: 'June 2026',
      verified: true,
    },
    description: l.name + ' is a UGC-approved private university in ' + l.city + ', Bangladesh.',
    campusImages: [
      'https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
  };
}

export const universities: University[] = [
  ...detailedUniversities,
  ...lightUnis.map(lightToFull),
];

export function getUniversityBySlug(slug: string): University | undefined {
  return universities.find((u) => u.slug === slug);
}

export function getFeaturedUniversities(): University[] {
  return detailedUniversities.slice(0, 6);
}

export function getStats() {
  const totalPrograms = universities.reduce((sum, u) => sum + u.programs.length, 0);
  const allTuitions = universities.flatMap((u) => u.programs.map((p) => p.tuitionPerCredit));
  const avgTuition = Math.round(allTuitions.reduce((a, b) => a + b, 0) / allTuitions.length);
  const minTuition = Math.min(...allTuitions);
  const maxTuition = Math.max(...allTuitions);
  const iebCount = universities.filter((u) => u.iebAccredited).length;
  const scholarshipCount = universities.filter((u) => u.hasScholarship).length;

  return {
    totalUniversities: universities.length,
    totalPrograms,
    avgTuition,
    minTuition,
    maxTuition,
    iebCount,
    scholarshipCount,
  };
}
